<?php
/**
 * SmsApi
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\FreeMobile\Sms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Free Mobile REST
 *
 * This is a Swagger generated doc for Free Mobile REST API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: security@free.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SiapepFrance\FreeMobile\Sms\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SiapepFrance\FreeMobile\Sms\ApiException;
use SiapepFrance\FreeMobile\Sms\Configuration;
use SiapepFrance\FreeMobile\Sms\HeaderSelector;
use SiapepFrance\FreeMobile\Sms\ObjectSerializer;

/**
 * SmsApi Class Doc Comment
 *
 * @category Class
 * @package  SiapepFrance\FreeMobile\Sms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation sendmsgPost
     *
     * Send a SMS to a user
     *
     * @param  string $user User of free mobile account (required)
     * @param  string $pass Password of free mobile account (required)
     * @param  string $msg Message to send (max length 999 caracters, above it will trigger 400 error) (required)
     *
     * @throws \SiapepFrance\FreeMobile\Sms\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function sendmsgPost($user, $pass, $msg)
    {
        $this->sendmsgPostWithHttpInfo($user, $pass, $msg);
    }

    /**
     * Operation sendmsgPostWithHttpInfo
     *
     * Send a SMS to a user
     *
     * @param  string $user User of free mobile account (required)
     * @param  string $pass Password of free mobile account (required)
     * @param  string $msg Message to send (max length 999 caracters, above it will trigger 400 error) (required)
     *
     * @throws \SiapepFrance\FreeMobile\Sms\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendmsgPostWithHttpInfo($user, $pass, $msg)
    {
        $returnType = '';
        $request = $this->sendmsgPostRequest($user, $pass, $msg);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation sendmsgPostAsync
     *
     * Send a SMS to a user
     *
     * @param  string $user User of free mobile account (required)
     * @param  string $pass Password of free mobile account (required)
     * @param  string $msg Message to send (max length 999 caracters, above it will trigger 400 error) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendmsgPostAsync($user, $pass, $msg)
    {
        return $this->sendmsgPostAsyncWithHttpInfo($user, $pass, $msg)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendmsgPostAsyncWithHttpInfo
     *
     * Send a SMS to a user
     *
     * @param  string $user User of free mobile account (required)
     * @param  string $pass Password of free mobile account (required)
     * @param  string $msg Message to send (max length 999 caracters, above it will trigger 400 error) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendmsgPostAsyncWithHttpInfo($user, $pass, $msg)
    {
        $returnType = '';
        $request = $this->sendmsgPostRequest($user, $pass, $msg);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendmsgPost'
     *
     * @param  string $user User of free mobile account (required)
     * @param  string $pass Password of free mobile account (required)
     * @param  string $msg Message to send (max length 999 caracters, above it will trigger 400 error) (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendmsgPostRequest($user, $pass, $msg)
    {
        // verify the required parameter 'user' is set
        if ($user === null || (is_array($user) && count($user) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user when calling sendmsgPost'
            );
        }
        // verify the required parameter 'pass' is set
        if ($pass === null || (is_array($pass) && count($pass) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $pass when calling sendmsgPost'
            );
        }
        // verify the required parameter 'msg' is set
        if ($msg === null || (is_array($msg) && count($msg) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $msg when calling sendmsgPost'
            );
        }

        $resourcePath = '/sendmsg';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($user !== null) {
            $queryParams['user'] = ObjectSerializer::toQueryValue($user);
        }
        // query params
        if ($pass !== null) {
            $queryParams['pass'] = ObjectSerializer::toQueryValue($pass);
        }
        // query params
        if ($msg !== null) {
            $queryParams['msg'] = ObjectSerializer::toQueryValue($msg);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
