<?php
/**
 * SmsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SiapepFrance\FreeMobile\Sms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Free Mobile REST
 *
 * This is a Swagger generated doc for Free Mobile REST API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: security@free.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SiapepFrance\FreeMobile\Sms;

use SiapepFrance\FreeMobile\Sms\Configuration;
use SiapepFrance\FreeMobile\Sms\ApiException;
use SiapepFrance\FreeMobile\Sms\ObjectSerializer;

/**
 * SmsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SiapepFrance\FreeMobile\Sms
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for sendmsgPost
     *
     * Send a SMS to a user.
     *
     */
    public function testSendmsgPost()
    {
    }
}
